/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ibiology;

import java.awt.KeyboardFocusManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author x14500057
 */
public class CrosswordGame extends javax.swing.JFrame {

    private ArrayList<CrosswordClass> aList;
   
   
   
    private StringBuffer buffAns1, buffAns2, buffAns3, buffAns4, buffAns5, buffAns6, buffAns7, buffAns8, buffAns9, buffAns10;
    private String finalAns1, finalAns2, finalAns3, finalAns4, finalAns5, finalAns6, finalAns7, finalAns8, finalAns9, finalAns10, finalAns11;
    private String player;
    private int score, count;

    public CrosswordGame() {
     
        score = 0;
        count = 0;
        player = new String();
    
        aList = new ArrayList<>();
       

        //One_1.setDocument(new JTFCharLimit(0b1));
        
        
        buffAns1 = new StringBuffer();
        buffAns2 = new StringBuffer();
        buffAns3 = new StringBuffer();
        buffAns4 = new StringBuffer();
        buffAns5 = new StringBuffer();
        buffAns6 = new StringBuffer();
        buffAns7 = new StringBuffer();
        buffAns8 = new StringBuffer();
        buffAns9 = new StringBuffer();
        buffAns10 = new StringBuffer();

        finalAns1 = new String();
        finalAns2 = new String();
        finalAns3 = new String();
        finalAns4 = new String();
        finalAns5 = new String();
        finalAns6 = new String();
        finalAns7 = new String();
        finalAns8 = new String();
        finalAns9 = new String();
        finalAns10 = new String();
        finalAns11 = new String();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiniB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();
        TopBar = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JLabel();
        one_1 = new javax.swing.JTextField();
        one_2 = new javax.swing.JTextField();
        one_3 = new javax.swing.JTextField();
        one_4 = new javax.swing.JTextField();
        one_5 = new javax.swing.JTextField();
        one_6 = new javax.swing.JTextField();
        one_7 = new javax.swing.JTextField();
        one_8 = new javax.swing.JTextField();
        two_2 = new javax.swing.JTextField();
        two_3 = new javax.swing.JTextField();
        two_4 = new javax.swing.JTextField();
        two_5 = new javax.swing.JTextField();
        two_6 = new javax.swing.JTextField();
        Three_1 = new javax.swing.JTextField();
        Three_2 = new javax.swing.JTextField();
        Three_3 = new javax.swing.JTextField();
        Three_4 = new javax.swing.JTextField();
        Three_5 = new javax.swing.JTextField();
        Three_6 = new javax.swing.JTextField();
        Four_1 = new javax.swing.JTextField();
        Four_2 = new javax.swing.JTextField();
        Four_3 = new javax.swing.JTextField();
        Four_4 = new javax.swing.JTextField();
        Four_5 = new javax.swing.JTextField();
        Four_6 = new javax.swing.JTextField();
        Four_7 = new javax.swing.JTextField();
        Five_1 = new javax.swing.JTextField();
        Five_2 = new javax.swing.JTextField();
        Five_3 = new javax.swing.JTextField();
        Five_4 = new javax.swing.JTextField();
        Six_1 = new javax.swing.JTextField();
        Six_2 = new javax.swing.JTextField();
        Six_3 = new javax.swing.JTextField();
        Six_4 = new javax.swing.JTextField();
        Six_5 = new javax.swing.JTextField();
        Six_6 = new javax.swing.JTextField();
        Six_7 = new javax.swing.JTextField();
        Six_8 = new javax.swing.JTextField();
        Six_9 = new javax.swing.JTextField();
        Six_10 = new javax.swing.JTextField();
        Six_11 = new javax.swing.JTextField();
        Seven_1 = new javax.swing.JTextField();
        Seven_3 = new javax.swing.JTextField();
        Seven_5 = new javax.swing.JTextField();
        Seven_6 = new javax.swing.JTextField();
        Seven_8 = new javax.swing.JTextField();
        Seven_10 = new javax.swing.JTextField();
        Seven_12 = new javax.swing.JTextField();
        Eight_1 = new javax.swing.JTextField();
        Eight_2 = new javax.swing.JTextField();
        Eight_3 = new javax.swing.JTextField();
        Eight_5 = new javax.swing.JTextField();
        Eight_6 = new javax.swing.JTextField();
        Eight_7 = new javax.swing.JTextField();
        Eight_8 = new javax.swing.JTextField();
        Eight_9 = new javax.swing.JTextField();
        Eight_10 = new javax.swing.JTextField();
        Nine_1 = new javax.swing.JTextField();
        Nine_2 = new javax.swing.JTextField();
        Nine_3 = new javax.swing.JTextField();
        Nine_4 = new javax.swing.JTextField();
        Nine_5 = new javax.swing.JTextField();
        Nine_6 = new javax.swing.JTextField();
        Nine_7 = new javax.swing.JTextField();
        Nine_9 = new javax.swing.JTextField();
        Nine_10 = new javax.swing.JTextField();
        Ten_1 = new javax.swing.JTextField();
        Ten_2 = new javax.swing.JTextField();
        Ten_4 = new javax.swing.JTextField();
        Ten_5 = new javax.swing.JTextField();
        Ten_6 = new javax.swing.JTextField();
        Ten_7 = new javax.swing.JTextField();
        Ten_8 = new javax.swing.JTextField();
        Ten_9 = new javax.swing.JTextField();
        Ten_10 = new javax.swing.JTextField();
        Ten_11 = new javax.swing.JTextField();
        AcrossLbl = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        Q5 = new javax.swing.JLabel();
        Down = new javax.swing.JLabel();
        Q6 = new javax.swing.JLabel();
        Q7 = new javax.swing.JLabel();
        Q8 = new javax.swing.JLabel();
        Q9 = new javax.swing.JLabel();
        Q10 = new javax.swing.JLabel();
        deleteAnswers = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        saveAnswersBtn = new javax.swing.JToggleButton();
        SaveBtn = new javax.swing.JButton();
        viewSavedBtn = new javax.swing.JButton();
        Layout = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MiniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniBMouseClicked(evt);
            }
        });
        getContentPane().add(MiniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 22, 20));

        CloseB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 10, 22, 20));

        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });
        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 22));

        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        one_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_1.setBorder(null);
        one_1.setOpaque(false);
        one_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_1KeyTyped(evt);
            }
        });
        getContentPane().add(one_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 24, 25));

        one_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_2.setBorder(null);
        one_2.setOpaque(false);
        one_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_2KeyTyped(evt);
            }
        });
        getContentPane().add(one_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 60, 25, 25));

        one_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_3.setBorder(null);
        one_3.setOpaque(false);
        one_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_3KeyTyped(evt);
            }
        });
        getContentPane().add(one_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 60, 24, 25));

        one_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_4.setBorder(null);
        one_4.setOpaque(false);
        one_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_4KeyTyped(evt);
            }
        });
        getContentPane().add(one_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 25, 25));

        one_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_5.setBorder(null);
        one_5.setOpaque(false);
        one_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_5KeyTyped(evt);
            }
        });
        getContentPane().add(one_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 60, 25, 25));

        one_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_6.setBorder(null);
        one_6.setOpaque(false);
        one_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_6KeyTyped(evt);
            }
        });
        getContentPane().add(one_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 60, 24, 25));

        one_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_7.setBorder(null);
        one_7.setOpaque(false);
        one_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_7KeyTyped(evt);
            }
        });
        getContentPane().add(one_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 60, 24, 25));

        one_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        one_8.setBorder(null);
        one_8.setOpaque(false);
        one_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                one_8KeyTyped(evt);
            }
        });
        getContentPane().add(one_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 60, 24, 25));

        two_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two_2.setBorder(null);
        two_2.setOpaque(false);
        two_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                two_2KeyTyped(evt);
            }
        });
        getContentPane().add(two_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 88, 24, 26));

        two_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two_3.setBorder(null);
        two_3.setOpaque(false);
        two_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                two_3KeyTyped(evt);
            }
        });
        getContentPane().add(two_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 120, 24, 26));

        two_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two_4.setBorder(null);
        two_4.setOpaque(false);
        two_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                two_4KeyTyped(evt);
            }
        });
        getContentPane().add(two_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 144, 24, 25));

        two_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two_5.setBorder(null);
        two_5.setOpaque(false);
        two_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                two_5KeyTyped(evt);
            }
        });
        getContentPane().add(two_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 170, 24, 25));

        two_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        two_6.setBorder(null);
        two_6.setOpaque(false);
        two_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                two_6KeyTyped(evt);
            }
        });
        getContentPane().add(two_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 200, 24, 25));

        Three_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_1.setBorder(null);
        Three_1.setOpaque(false);
        Three_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_1KeyTyped(evt);
            }
        });
        getContentPane().add(Three_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 114, 24, 26));

        Three_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_2.setBorder(null);
        Three_2.setOpaque(false);
        Three_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_2KeyTyped(evt);
            }
        });
        getContentPane().add(Three_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 144, 24, 26));

        Three_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_3.setBorder(null);
        Three_3.setOpaque(false);
        Three_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_3KeyTyped(evt);
            }
        });
        getContentPane().add(Three_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 170, 24, 26));

        Three_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_4.setBorder(null);
        Three_4.setOpaque(false);
        Three_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_4KeyTyped(evt);
            }
        });
        getContentPane().add(Three_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 200, 24, 26));

        Three_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_5.setBorder(null);
        Three_5.setOpaque(false);
        Three_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_5KeyTyped(evt);
            }
        });
        getContentPane().add(Three_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 230, 24, 26));

        Three_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Three_6.setBorder(null);
        Three_6.setOpaque(false);
        Three_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Three_6KeyTyped(evt);
            }
        });
        getContentPane().add(Three_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 254, 24, 26));

        Four_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_1.setBorder(null);
        Four_1.setOpaque(false);
        Four_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_1KeyTyped(evt);
            }
        });
        getContentPane().add(Four_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 142, 24, 26));

        Four_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_2.setBorder(null);
        Four_2.setOpaque(false);
        Four_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_2KeyTyped(evt);
            }
        });
        getContentPane().add(Four_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 170, 24, 26));

        Four_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_3.setBorder(null);
        Four_3.setOpaque(false);
        Four_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_3KeyTyped(evt);
            }
        });
        getContentPane().add(Four_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 200, 24, 26));

        Four_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_4.setBorder(null);
        Four_4.setOpaque(false);
        Four_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_4KeyTyped(evt);
            }
        });
        getContentPane().add(Four_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 230, 24, 26));

        Four_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_5.setBorder(null);
        Four_5.setOpaque(false);
        Four_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_5KeyTyped(evt);
            }
        });
        getContentPane().add(Four_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 258, 24, 26));

        Four_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_6.setBorder(null);
        Four_6.setOpaque(false);
        Four_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_6KeyTyped(evt);
            }
        });
        getContentPane().add(Four_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 282, 24, 26));

        Four_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Four_7.setBorder(null);
        Four_7.setOpaque(false);
        Four_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Four_7KeyTyped(evt);
            }
        });
        getContentPane().add(Four_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 310, 24, 26));

        Five_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Five_1.setBorder(null);
        Five_1.setOpaque(false);
        Five_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Five_1KeyTyped(evt);
            }
        });
        getContentPane().add(Five_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 24, 26));

        Five_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Five_2.setBorder(null);
        Five_2.setOpaque(false);
        Five_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Five_2KeyTyped(evt);
            }
        });
        getContentPane().add(Five_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 24, 26));

        Five_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Five_3.setBorder(null);
        Five_3.setOpaque(false);
        Five_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Five_3KeyTyped(evt);
            }
        });
        getContentPane().add(Five_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 24, 26));

        Five_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Five_4.setBorder(null);
        Five_4.setOpaque(false);
        Five_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Five_4KeyTyped(evt);
            }
        });
        getContentPane().add(Five_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 24, 26));

        Six_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_1.setBorder(null);
        Six_1.setOpaque(false);
        Six_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_1KeyTyped(evt);
            }
        });
        getContentPane().add(Six_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 144, 24, 26));

        Six_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_2.setBorder(null);
        Six_2.setOpaque(false);
        Six_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_2KeyTyped(evt);
            }
        });
        getContentPane().add(Six_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 24, 26));

        Six_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_3.setBorder(null);
        Six_3.setOpaque(false);
        Six_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_3KeyTyped(evt);
            }
        });
        getContentPane().add(Six_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 24, 26));

        Six_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_4.setBorder(null);
        Six_4.setOpaque(false);
        Six_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_4KeyTyped(evt);
            }
        });
        getContentPane().add(Six_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 24, 26));

        Six_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_5.setBorder(null);
        Six_5.setOpaque(false);
        Six_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_5KeyTyped(evt);
            }
        });
        getContentPane().add(Six_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 258, 24, 26));

        Six_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_6.setBorder(null);
        Six_6.setOpaque(false);
        Six_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_6KeyTyped(evt);
            }
        });
        getContentPane().add(Six_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 24, 26));

        Six_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_7.setBorder(null);
        Six_7.setOpaque(false);
        Six_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_7KeyTyped(evt);
            }
        });
        getContentPane().add(Six_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 24, 26));

        Six_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_8.setBorder(null);
        Six_8.setOpaque(false);
        Six_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_8KeyTyped(evt);
            }
        });
        getContentPane().add(Six_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 24, 26));

        Six_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_9.setBorder(null);
        Six_9.setOpaque(false);
        Six_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_9KeyTyped(evt);
            }
        });
        getContentPane().add(Six_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 24, 26));

        Six_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_10.setBorder(null);
        Six_10.setOpaque(false);
        Six_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_10KeyTyped(evt);
            }
        });
        getContentPane().add(Six_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 24, 26));

        Six_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Six_11.setBorder(null);
        Six_11.setOpaque(false);
        Six_11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Six_11KeyTyped(evt);
            }
        });
        getContentPane().add(Six_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 424, 24, 26));

        Seven_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_1.setBorder(null);
        Seven_1.setOpaque(false);
        Seven_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_1KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 24, 26));

        Seven_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_3.setBorder(null);
        Seven_3.setOpaque(false);
        Seven_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_3KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 24, 26));

        Seven_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_5.setBorder(null);
        Seven_5.setOpaque(false);
        Seven_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_5KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 24, 26));

        Seven_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_6.setBorder(null);
        Seven_6.setOpaque(false);
        Seven_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_6KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 170, 24, 26));

        Seven_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_8.setBorder(null);
        Seven_8.setOpaque(false);
        Seven_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_8KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 24, 26));

        Seven_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_10.setBorder(null);
        Seven_10.setOpaque(false);
        Seven_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_10KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 170, 24, 26));

        Seven_12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Seven_12.setBorder(null);
        Seven_12.setOpaque(false);
        Seven_12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Seven_12KeyTyped(evt);
            }
        });
        getContentPane().add(Seven_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 24, 26));

        Eight_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_1.setBorder(null);
        Eight_1.setOpaque(false);
        Eight_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_1KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 310, 24, 26));

        Eight_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_2.setBorder(null);
        Eight_2.setOpaque(false);
        Eight_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_2KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 24, 26));

        Eight_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_3.setBorder(null);
        Eight_3.setOpaque(false);
        Eight_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_3KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 24, 26));

        Eight_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_5.setBorder(null);
        Eight_5.setOpaque(false);
        Eight_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_5KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 310, 24, 26));

        Eight_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_6.setBorder(null);
        Eight_6.setOpaque(false);
        Eight_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_6KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 310, 24, 26));

        Eight_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_7.setBorder(null);
        Eight_7.setOpaque(false);
        Eight_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_7KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 24, 26));

        Eight_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_8.setBorder(null);
        Eight_8.setOpaque(false);
        Eight_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_8KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 310, 24, 26));

        Eight_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_9.setBorder(null);
        Eight_9.setOpaque(false);
        Eight_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_9KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 310, 24, 26));

        Eight_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eight_10.setBorder(null);
        Eight_10.setOpaque(false);
        Eight_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Eight_10KeyTyped(evt);
            }
        });
        getContentPane().add(Eight_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 310, 24, 26));

        Nine_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_1.setBorder(null);
        Nine_1.setOpaque(false);
        Nine_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_1KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 370, 24, 26));

        Nine_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_2.setBorder(null);
        Nine_2.setOpaque(false);
        Nine_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_2KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 370, 24, 26));

        Nine_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_3.setBorder(null);
        Nine_3.setOpaque(false);
        Nine_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_3KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 24, 26));

        Nine_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_4.setBorder(null);
        Nine_4.setOpaque(false);
        Nine_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_4KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 24, 26));

        Nine_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_5.setBorder(null);
        Nine_5.setOpaque(false);
        Nine_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_5KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 370, 24, 26));

        Nine_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_6.setBorder(null);
        Nine_6.setOpaque(false);
        Nine_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_6KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 370, 24, 26));

        Nine_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_7.setBorder(null);
        Nine_7.setOpaque(false);
        Nine_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_7KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 24, 26));

        Nine_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_9.setBorder(null);
        Nine_9.setOpaque(false);
        Nine_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_9KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 370, 24, 26));

        Nine_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nine_10.setBorder(null);
        Nine_10.setOpaque(false);
        Nine_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nine_10KeyTyped(evt);
            }
        });
        getContentPane().add(Nine_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 370, 24, 26));

        Ten_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_1.setBorder(null);
        Ten_1.setOpaque(false);
        Ten_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_1KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 424, 24, 26));

        Ten_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_2.setBorder(null);
        Ten_2.setOpaque(false);
        Ten_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_2KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 424, 24, 26));

        Ten_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_4.setBorder(null);
        Ten_4.setOpaque(false);
        Ten_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_4KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 424, 24, 26));

        Ten_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_5.setBorder(null);
        Ten_5.setOpaque(false);
        Ten_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_5KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 424, 24, 26));

        Ten_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_6.setBorder(null);
        Ten_6.setOpaque(false);
        Ten_6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_6KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 424, 24, 26));

        Ten_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_7.setBorder(null);
        Ten_7.setOpaque(false);
        Ten_7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_7KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 424, 24, 26));

        Ten_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_8.setBorder(null);
        Ten_8.setOpaque(false);
        Ten_8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_8KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 424, 24, 26));

        Ten_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_9.setBorder(null);
        Ten_9.setOpaque(false);
        Ten_9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_9KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 424, 24, 26));

        Ten_10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_10.setBorder(null);
        Ten_10.setOpaque(false);
        Ten_10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_10KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 424, 24, 26));

        Ten_11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ten_11.setBorder(null);
        Ten_11.setOpaque(false);
        Ten_11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ten_11KeyTyped(evt);
            }
        });
        getContentPane().add(Ten_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 424, 24, 26));

        AcrossLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AcrossLbl.setForeground(new java.awt.Color(255, 255, 255));
        AcrossLbl.setText("Across:");
        getContentPane().add(AcrossLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 50, 20));

        Q1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setText("Q1:Process in which stem cells multiply?");
        getContentPane().add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 20));

        Q2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setText("Q7:Blood leaving the heart is?");
        getContentPane().add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 190, 20));

        Q3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q3.setForeground(new java.awt.Color(255, 255, 255));
        Q3.setText("Q8:Another name for a blood cell?");
        getContentPane().add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 20));

        Q4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Q4.setForeground(new java.awt.Color(255, 255, 255));
        Q4.setText("Q9:Process in which the liver is actively involved?");
        getContentPane().add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 20));

        Q5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Q5.setForeground(new java.awt.Color(255, 255, 255));
        Q5.setText("Q10:Sytem responsible for gas exchanges?");
        getContentPane().add(Q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 240, 20));

        Down.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Down.setForeground(new java.awt.Color(255, 255, 255));
        Down.setText("Down:");
        getContentPane().add(Down, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 50, 20));

        Q6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q6.setForeground(new java.awt.Color(255, 255, 255));
        Q6.setText("Q3:Where does gas exhanges take place?");
        getContentPane().add(Q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 260, 20));

        Q7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q7.setForeground(new java.awt.Color(255, 255, 255));
        Q7.setText("Q4:What does \"C\" stand for in CNS?");
        getContentPane().add(Q7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 250, 20));

        Q8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q8.setForeground(new java.awt.Color(255, 255, 255));
        Q8.setText("Q5:Long slender part of neurone?");
        getContentPane().add(Q8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 250, 20));

        Q9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q9.setForeground(new java.awt.Color(255, 255, 255));
        Q9.setText("Q6:Tiny vessels connecting arterholes and venules?");
        getContentPane().add(Q9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 350, 20));

        Q10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Q10.setForeground(new java.awt.Color(255, 255, 255));
        Q10.setText("Q2:Stops backflow of blood to the heart?");
        getContentPane().add(Q10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 270, 20));

        deleteAnswers.setText("Delete Answers");
        deleteAnswers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAnswersActionPerformed(evt);
            }
        });
        getContentPane().add(deleteAnswers, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 150, 35));

        SearchBtn.setText("Search Scores");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 120, 35));

        saveAnswersBtn.setText("Save Answers");
        saveAnswersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAnswersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveAnswersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 140, 35));

        SaveBtn.setText("Save to File");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 110, 35));

        viewSavedBtn.setText("View Saved");
        viewSavedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSavedBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewSavedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 130, 35));

        Layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/CrosswordLayout.png"))); // NOI18N
        getContentPane().add(Layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 710, 520));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/OOP_GUI_Template.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        setSize(new java.awt.Dimension(858, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MiniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniBMouseClicked
        this.setState(CrosswordGame.ICONIFIED);
    }//GEN-LAST:event_MiniBMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

    }//GEN-LAST:event_formMouseDragged

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        HomePageGUI GUI = new HomePageGUI();
        GUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void saveAnswersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAnswersBtnActionPerformed
        
        finalAns1 = buffAns1.append(one_1.getText())
                .append(one_2.getText())
                .append(one_3.getText())
                .append(one_4.getText())
                .append(one_5.getText())
                .append(one_6.getText())
                .append(one_7.getText())
                .append(one_8.getText())
                .toString();
        
        finalAns2 = buffAns2.append(one_3.getText())
                .append(two_2.getText())
                .append(two_3.getText())
                .append(two_4.getText())
                .append(two_5.getText())
                .append(two_6.getText())
                .toString();
                
        finalAns3 = buffAns3.append(Three_1.getText())
                .append(Three_2.getText())
                .append(Three_3.getText())
                .append(Three_4.getText())
                .append(Three_5.getText())
                .append(Three_6.getText())
                .toString();
        
        finalAns4 = buffAns4.append(Four_1.getText())
                .append(Four_2.getText())
                .append(Four_3.getText())
                .append(Four_4.getText())
                .append(Four_5.getText())
                .append(Four_6.getText())
                .append(Four_7.getText())
                .toString();
        
       finalAns5 = buffAns5.append(Five_1.getText())
                .append(Five_2.getText())
                .append(Five_3.getText())
                .append(Five_4.getText())
                .toString();
               
       finalAns6 = buffAns6.append(Six_1.getText())
                .append(Six_2.getText())
                .append(Six_3.getText())
                .append(Six_4.getText())
                .append(Six_5.getText())
                .append(Six_6.getText())
                .append(Six_7.getText())
                .append(Six_8.getText())
                .append(Six_9.getText())
                .append(Six_10.getText())
                .append(Six_11.getText())
                .toString();
       
        finalAns7 = buffAns7.append(Seven_1.getText())
               .append(Four_2.getText())
               .append(Seven_3.getText())
               .append(Six_4.getText())
               .append(Five_2.getText())
               .append(Seven_5.getText())
               .append(Seven_6.getText())
               .append(two_5.getText())
               .append(Seven_8.getText())
               .append(Six_2.getText())
               .append(Seven_10.getText())
               .append(Three_3.getText())
               .append(Seven_12.getText())
               .toString();
        
        finalAns8 = buffAns8.append(Eight_1.getText())
               .append(Eight_2.getText())
               .append(Eight_3.getText())
               .append(Six_7.getText())
               .append(Eight_5.getText())
               .append(Eight_6.getText())
               .append(Eight_7.getText())
               .append(Eight_8.getText())
               .append(Eight_9.getText())
               .append(Eight_10.getText())
               .toString();
        
         finalAns9= buffAns9.append(Nine_1.getText())
               .append(Nine_2.getText())
               .append(Nine_3.getText())
               .append(Nine_4.getText())
               .append(Nine_5.getText())
               .append(Nine_6.getText())
               .append(Nine_7.getText())
               .append(Six_9.getText())
               .append(Nine_9.getText())
               .append(Nine_10.getText())
               .toString();
         
          finalAns10= buffAns10.append(Ten_1.getText())
               .append(Ten_2.getText())
               .append(Six_11.getText())
               .append(Ten_4.getText())
               .append(Ten_5.getText())
               .append(Ten_6.getText())
               .append(Ten_7.getText())
               .append(Ten_8.getText())
               .append(Ten_9.getText())
               .append(Ten_10.getText())
               .append(Ten_11.getText())
               .toString();

        //score
        if (finalAns1.equalsIgnoreCase("division")) {
            score++;
        }
        if (finalAns2.equalsIgnoreCase("valves")) {
            score++;
        }
        if (finalAns3.equalsIgnoreCase("aleoli")) {
            score++;
        }
        if (finalAns4.equalsIgnoreCase("central")) {
            score++;
        }
        if (finalAns5.equalsIgnoreCase("axon")) {
            score++;
        }
        if (finalAns6.equalsIgnoreCase("capillaries")) {
            score++;
        }
        if (finalAns7.equalsIgnoreCase("deoxygenated")) {
            score++;
        }
        if (finalAns8.equalsIgnoreCase("hematocyte")) {
            score++;
        }
        if (finalAns9.equalsIgnoreCase("metabolism")) {
            score++;
        }
        if (finalAns10.equalsIgnoreCase("respiratory")) {
            score++;
        }

        //instance
        CrosswordClass c = new CrosswordClass();
        //player name
        player = JOptionPane.showInputDialog(null, "enter your name");
        //add to the array list
        c.setFinalAns1(finalAns1);
        c.setFinalAns2(finalAns2);
        c.setFinalAns3(finalAns3);
        c.setFinalAns4(finalAns4);
        c.setFinalAns5(finalAns5);
        c.setFinalAns6(finalAns6);
        c.setFinalAns7(finalAns7);
        c.setFinalAns8(finalAns8);
        c.setFinalAns9(finalAns9);
        c.setFinalAns10(finalAns10);
        c.setPlayer(player);
        c.setScore(score);
        //add object to arraylist
        aList.add(c);
        //increment 
        count++;
        //increments when somethings added  
    }//GEN-LAST:event_saveAnswersBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
   if (finalAns1.equals("") && finalAns2.equals("") && finalAns3.equals("") && finalAns4.equals("") && finalAns5.equals("")
                && finalAns6.equals("") && finalAns7.equals("") && finalAns8.equals("")
                && finalAns9.equals("") && finalAns10.equals("")) {
            JOptionPane.showMessageDialog(null, "you haven't entered anything so you have nothing to do delete!!");  
        }    
    String searchPlayer=JOptionPane.showInputDialog(null,"Enter your name: ");
        for(int i=0; i<aList.size();i++){
            if(searchPlayer.equals(player)){
                JOptionPane.showMessageDialog(null, player+"'s score is "+score);
            }
            
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_TopBarMouseDragged

    private void deleteAnswersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAnswersActionPerformed
        String delAnswer;
        delAnswer = JOptionPane.showInputDialog(null, "what answer would you like to delete?(numeric value)");
        if (delAnswer.equals(" ")) {
            JOptionPane.showMessageDialog(null, "you have not entered anything");
        }
        for (int i = 0; i < aList.size(); i++) {
            if (delAnswer.equalsIgnoreCase("1")) {
                aList.remove(i).getFinalAns1();
            }
            if (delAnswer.equalsIgnoreCase("2")) {
                aList.remove(i).getFinalAns2();
            }
            if (delAnswer.equalsIgnoreCase("3")) {
                aList.remove(i).getFinalAns3();
            }
            if (delAnswer.equalsIgnoreCase("4")) {
                aList.remove(i).getFinalAns4();
            }
            if (delAnswer.equalsIgnoreCase("5")) {
                aList.remove(i).getFinalAns5();
            }
            if (delAnswer.equalsIgnoreCase("6")) {
                aList.remove(i).getFinalAns6();
            }
            if (delAnswer.equalsIgnoreCase("7")) {
                aList.remove(i).getFinalAns7();
            }
            if (delAnswer.equalsIgnoreCase("8")) {
                aList.remove(i).getFinalAns8();
            }
            if (delAnswer.equalsIgnoreCase("9")) {
                aList.remove(i).getFinalAns9();
            }
            if (delAnswer.equalsIgnoreCase("10")) {
                aList.remove(i).getFinalAns10();
            }
        }
    }//GEN-LAST:event_deleteAnswersActionPerformed
    //jumps  to the next textfield
    //colm bennett helped me with this
    private void one_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_1KeyTyped
        captureKey(evt, one_1.getText().isEmpty());
    }//GEN-LAST:event_one_1KeyTyped

    private void one_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_2KeyTyped
        captureKey(evt, one_2.getText().isEmpty());
    }//GEN-LAST:event_one_2KeyTyped

    private void one_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_3KeyTyped
        captureKey(evt, one_3.getText().isEmpty());
    }//GEN-LAST:event_one_3KeyTyped

    private void one_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_4KeyTyped
        captureKey(evt, one_4.getText().isEmpty());
    }//GEN-LAST:event_one_4KeyTyped

    private void one_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_5KeyTyped
        captureKey(evt, one_5.getText().isEmpty());
    }//GEN-LAST:event_one_5KeyTyped

    private void one_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_6KeyTyped
        captureKey(evt, one_6.getText().isEmpty());
    }//GEN-LAST:event_one_6KeyTyped

    private void one_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_7KeyTyped
        captureKey(evt, one_7.getText().isEmpty());
    }//GEN-LAST:event_one_7KeyTyped

    private void one_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_one_8KeyTyped
        captureKey(evt, one_8.getText().isEmpty());
    }//GEN-LAST:event_one_8KeyTyped

    private void two_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_two_2KeyTyped
        captureKey(evt, two_2.getText().isEmpty());
    }//GEN-LAST:event_two_2KeyTyped

    private void two_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_two_3KeyTyped
        captureKey(evt, two_3.getText().isEmpty());
    }//GEN-LAST:event_two_3KeyTyped

    private void two_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_two_4KeyTyped
        captureKey(evt, two_4.getText().isEmpty());
    }//GEN-LAST:event_two_4KeyTyped

    private void two_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_two_5KeyTyped
        captureKey(evt, two_5.getText().isEmpty());
    }//GEN-LAST:event_two_5KeyTyped

    private void two_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_two_6KeyTyped
        captureKey(evt, two_6.getText().isEmpty());
    }//GEN-LAST:event_two_6KeyTyped

    private void Three_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_1KeyTyped
        captureKey(evt, Three_1.getText().isEmpty());
    }//GEN-LAST:event_Three_1KeyTyped

    private void Three_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_2KeyTyped
        captureKey(evt, Three_2.getText().isEmpty());
    }//GEN-LAST:event_Three_2KeyTyped

    private void Three_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_3KeyTyped
        captureKey(evt, Three_3.getText().isEmpty());
    }//GEN-LAST:event_Three_3KeyTyped

    private void Three_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_4KeyTyped
        captureKey(evt, Three_4.getText().isEmpty());
    }//GEN-LAST:event_Three_4KeyTyped

    private void Three_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_5KeyTyped
        captureKey(evt, Three_5.getText().isEmpty());
    }//GEN-LAST:event_Three_5KeyTyped

    private void Three_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Three_6KeyTyped
        captureKey(evt, Three_6.getText().isEmpty());
    }//GEN-LAST:event_Three_6KeyTyped

    private void Four_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_1KeyTyped
        captureKey(evt, Four_1.getText().isEmpty());
    }//GEN-LAST:event_Four_1KeyTyped

    private void Four_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_2KeyTyped
        captureKey(evt, Four_2.getText().isEmpty());
    }//GEN-LAST:event_Four_2KeyTyped

    private void Four_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_3KeyTyped
        captureKey(evt, Four_3.getText().isEmpty());
    }//GEN-LAST:event_Four_3KeyTyped

    private void Four_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_4KeyTyped
        captureKey(evt, Four_4.getText().isEmpty());
    }//GEN-LAST:event_Four_4KeyTyped

    private void Four_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_5KeyTyped
        captureKey(evt, Four_5.getText().isEmpty());
    }//GEN-LAST:event_Four_5KeyTyped

    private void Four_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_6KeyTyped
        captureKey(evt, Four_6.getText().isEmpty());
    }//GEN-LAST:event_Four_6KeyTyped

    private void Four_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Four_7KeyTyped
        captureKey(evt, Four_7.getText().isEmpty());
    }//GEN-LAST:event_Four_7KeyTyped

    private void Five_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Five_1KeyTyped
        captureKey(evt, Five_1.getText().isEmpty());
    }//GEN-LAST:event_Five_1KeyTyped

    private void Five_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Five_2KeyTyped
        captureKey(evt, Five_2.getText().isEmpty());
    }//GEN-LAST:event_Five_2KeyTyped

    private void Five_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Five_3KeyTyped
        captureKey(evt, Five_3.getText().isEmpty());
    }//GEN-LAST:event_Five_3KeyTyped

    private void Five_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Five_4KeyTyped
        captureKey(evt, Five_4.getText().isEmpty());
    }//GEN-LAST:event_Five_4KeyTyped

    private void Six_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_1KeyTyped
        captureKey(evt, Six_1.getText().isEmpty());
    }//GEN-LAST:event_Six_1KeyTyped

    private void Six_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_2KeyTyped
        captureKey(evt, Six_2.getText().isEmpty());
    }//GEN-LAST:event_Six_2KeyTyped

    private void Six_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_3KeyTyped
        captureKey(evt, Six_3.getText().isEmpty());
    }//GEN-LAST:event_Six_3KeyTyped

    private void Six_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_4KeyTyped
        captureKey(evt, Six_4.getText().isEmpty());
    }//GEN-LAST:event_Six_4KeyTyped

    private void Six_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_5KeyTyped
        captureKey(evt, Six_5.getText().isEmpty());
    }//GEN-LAST:event_Six_5KeyTyped

    private void Six_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_6KeyTyped
        captureKey(evt, Six_6.getText().isEmpty());
    }//GEN-LAST:event_Six_6KeyTyped

    private void Six_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_7KeyTyped
        captureKey(evt, Six_7.getText().isEmpty());
    }//GEN-LAST:event_Six_7KeyTyped

    private void Six_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_8KeyTyped
        captureKey(evt, Six_8.getText().isEmpty());
    }//GEN-LAST:event_Six_8KeyTyped

    private void Six_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_9KeyTyped
        captureKey(evt, Six_9.getText().isEmpty());
    }//GEN-LAST:event_Six_9KeyTyped

    private void Six_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_10KeyTyped
        captureKey(evt, Six_10.getText().isEmpty());
    }//GEN-LAST:event_Six_10KeyTyped

    private void Six_11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Six_11KeyTyped
        captureKey(evt, Six_11.getText().isEmpty());
    }//GEN-LAST:event_Six_11KeyTyped

    private void Seven_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_1KeyTyped
        captureKey(evt, Seven_1.getText().isEmpty());
    }//GEN-LAST:event_Seven_1KeyTyped

    private void Seven_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_3KeyTyped
        captureKey(evt, Seven_3.getText().isEmpty());
    }//GEN-LAST:event_Seven_3KeyTyped

    private void Seven_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_5KeyTyped
        captureKey(evt, Seven_5.getText().isEmpty());
    }//GEN-LAST:event_Seven_5KeyTyped

    private void Seven_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_6KeyTyped
        captureKey(evt, Seven_6.getText().isEmpty());
    }//GEN-LAST:event_Seven_6KeyTyped

    private void Seven_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_8KeyTyped
        captureKey(evt, Seven_8.getText().isEmpty());
    }//GEN-LAST:event_Seven_8KeyTyped

    private void Seven_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_10KeyTyped
        captureKey(evt, Seven_10.getText().isEmpty());
    }//GEN-LAST:event_Seven_10KeyTyped

    private void Seven_12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Seven_12KeyTyped
        captureKey(evt, Seven_12.getText().isEmpty());
    }//GEN-LAST:event_Seven_12KeyTyped

    private void Eight_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_1KeyTyped
        captureKey(evt, Eight_1.getText().isEmpty());
    }//GEN-LAST:event_Eight_1KeyTyped

    private void Eight_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_2KeyTyped
        captureKey(evt, Eight_2.getText().isEmpty());
    }//GEN-LAST:event_Eight_2KeyTyped

    private void Eight_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_3KeyTyped
        captureKey(evt, Eight_3.getText().isEmpty());
    }//GEN-LAST:event_Eight_3KeyTyped

    private void Eight_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_5KeyTyped
        captureKey(evt, Eight_5.getText().isEmpty());
    }//GEN-LAST:event_Eight_5KeyTyped

    private void Eight_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_6KeyTyped
        captureKey(evt, Eight_6.getText().isEmpty());
    }//GEN-LAST:event_Eight_6KeyTyped

    private void Eight_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_7KeyTyped
        captureKey(evt, Eight_7.getText().isEmpty());
    }//GEN-LAST:event_Eight_7KeyTyped

    private void Eight_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_8KeyTyped
        captureKey(evt, Eight_8.getText().isEmpty());
    }//GEN-LAST:event_Eight_8KeyTyped

    private void Eight_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_9KeyTyped
        captureKey(evt, Eight_9.getText().isEmpty());
    }//GEN-LAST:event_Eight_9KeyTyped

    private void Eight_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Eight_10KeyTyped
        captureKey(evt, Eight_10.getText().isEmpty());
    }//GEN-LAST:event_Eight_10KeyTyped

    private void Nine_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_1KeyTyped
        captureKey(evt, Nine_1.getText().isEmpty());
    }//GEN-LAST:event_Nine_1KeyTyped

    private void Nine_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_2KeyTyped
        captureKey(evt, Nine_2.getText().isEmpty());
    }//GEN-LAST:event_Nine_2KeyTyped

    private void Nine_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_3KeyTyped
        captureKey(evt, Nine_3.getText().isEmpty());
    }//GEN-LAST:event_Nine_3KeyTyped

    private void Nine_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_4KeyTyped
        captureKey(evt, Nine_4.getText().isEmpty());
    }//GEN-LAST:event_Nine_4KeyTyped

    private void Nine_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_5KeyTyped
        captureKey(evt, Nine_5.getText().isEmpty());
    }//GEN-LAST:event_Nine_5KeyTyped

    private void Nine_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_6KeyTyped
        captureKey(evt, Nine_6.getText().isEmpty());
    }//GEN-LAST:event_Nine_6KeyTyped

    private void Nine_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_7KeyTyped
        captureKey(evt, Nine_7.getText().isEmpty());
    }//GEN-LAST:event_Nine_7KeyTyped

    private void Nine_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_9KeyTyped
        captureKey(evt, Nine_9.getText().isEmpty());
    }//GEN-LAST:event_Nine_9KeyTyped

    private void Nine_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nine_10KeyTyped
        captureKey(evt, Nine_10.getText().isEmpty());
    }//GEN-LAST:event_Nine_10KeyTyped

    private void Ten_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_1KeyTyped
        captureKey(evt, Ten_1.getText().isEmpty());
    }//GEN-LAST:event_Ten_1KeyTyped

    private void Ten_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_2KeyTyped
        captureKey(evt, Ten_2.getText().isEmpty());
    }//GEN-LAST:event_Ten_2KeyTyped

    private void Ten_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_4KeyTyped
        captureKey(evt, Ten_4.getText().isEmpty());
    }//GEN-LAST:event_Ten_4KeyTyped

    private void Ten_5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_5KeyTyped
        captureKey(evt, Ten_5.getText().isEmpty());
    }//GEN-LAST:event_Ten_5KeyTyped

    private void Ten_6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_6KeyTyped
        captureKey(evt, Ten_6.getText().isEmpty());
    }//GEN-LAST:event_Ten_6KeyTyped

    private void Ten_7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_7KeyTyped
        captureKey(evt, Ten_7.getText().isEmpty());
    }//GEN-LAST:event_Ten_7KeyTyped

    private void Ten_8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_8KeyTyped
        captureKey(evt, Ten_8.getText().isEmpty());
    }//GEN-LAST:event_Ten_8KeyTyped

    private void Ten_9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_9KeyTyped
        captureKey(evt, Ten_9.getText().isEmpty());
    }//GEN-LAST:event_Ten_9KeyTyped

    private void Ten_10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_10KeyTyped
        captureKey(evt, Ten_10.getText().isEmpty());
    }//GEN-LAST:event_Ten_10KeyTyped

    private void Ten_11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ten_11KeyTyped
        captureKey(evt, Ten_11.getText().isEmpty());
    }//GEN-LAST:event_Ten_11KeyTyped

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
    CrosswordClass c = new CrosswordClass();
    c.setScore(score);
    c.setPlayer(player);
    
    File outFile;
    FileOutputStream fStream;
    ObjectOutputStream oStream;
    
    try{
        outFile = new File ("output.data");
        fStream = new FileOutputStream (outFile);
        oStream = new ObjectOutputStream(fStream);
        
        oStream.writeObject(aList);
        JOptionPane.showMessageDialog(null, "file written succesfully");    
        
        oStream.close();
    }
    
    catch(IOException e){
        System.out.print(e);
        
    }
    
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void viewSavedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSavedBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            //CrosswordClass w;
            //w =(CrosswordClass)oStream.readObject();
            ArrayList<CrosswordClass> xList;
            xList = (ArrayList<CrosswordClass>)oStream.readObject();
            
            for(CrosswordClass x:xList ){
                JOptionPane.showMessageDialog(null,"Name: "+x.getPlayer()+" \n score: "+ x.getScore());
                }
                oStream.close();
        }
        
        catch(IOException | ClassNotFoundException e){
            System.out.print(e);
        } 
        
        
        
    }//GEN-LAST:event_viewSavedBtnActionPerformed

    /**
     *
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrosswordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrosswordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrosswordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrosswordGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }
    //method for jumping to next textfield
    //colm benett helped me with this
    private void captureKey(java.awt.event.KeyEvent evt, boolean empty) {
        if (empty) {

            KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            manager.focusNextComponent();

        } // TODO add your handling code here:
        else {
            evt.consume();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcrossLbl;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel Down;
    private javax.swing.JTextField Eight_1;
    private javax.swing.JTextField Eight_10;
    private javax.swing.JTextField Eight_2;
    private javax.swing.JTextField Eight_3;
    private javax.swing.JTextField Eight_5;
    private javax.swing.JTextField Eight_6;
    private javax.swing.JTextField Eight_7;
    private javax.swing.JTextField Eight_8;
    private javax.swing.JTextField Eight_9;
    private javax.swing.JTextField Five_1;
    private javax.swing.JTextField Five_2;
    private javax.swing.JTextField Five_3;
    private javax.swing.JTextField Five_4;
    private javax.swing.JTextField Four_1;
    private javax.swing.JTextField Four_2;
    private javax.swing.JTextField Four_3;
    private javax.swing.JTextField Four_4;
    private javax.swing.JTextField Four_5;
    private javax.swing.JTextField Four_6;
    private javax.swing.JTextField Four_7;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JLabel Layout;
    private javax.swing.JLabel MiniB;
    private javax.swing.JTextField Nine_1;
    private javax.swing.JTextField Nine_10;
    private javax.swing.JTextField Nine_2;
    private javax.swing.JTextField Nine_3;
    private javax.swing.JTextField Nine_4;
    private javax.swing.JTextField Nine_5;
    private javax.swing.JTextField Nine_6;
    private javax.swing.JTextField Nine_7;
    private javax.swing.JTextField Nine_9;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q10;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Q6;
    private javax.swing.JLabel Q7;
    private javax.swing.JLabel Q8;
    private javax.swing.JLabel Q9;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField Seven_1;
    private javax.swing.JTextField Seven_10;
    private javax.swing.JTextField Seven_12;
    private javax.swing.JTextField Seven_3;
    private javax.swing.JTextField Seven_5;
    private javax.swing.JTextField Seven_6;
    private javax.swing.JTextField Seven_8;
    private javax.swing.JTextField Six_1;
    private javax.swing.JTextField Six_10;
    private javax.swing.JTextField Six_11;
    private javax.swing.JTextField Six_2;
    private javax.swing.JTextField Six_3;
    private javax.swing.JTextField Six_4;
    private javax.swing.JTextField Six_5;
    private javax.swing.JTextField Six_6;
    private javax.swing.JTextField Six_7;
    private javax.swing.JTextField Six_8;
    private javax.swing.JTextField Six_9;
    private javax.swing.JTextField Ten_1;
    private javax.swing.JTextField Ten_10;
    private javax.swing.JTextField Ten_11;
    private javax.swing.JTextField Ten_2;
    private javax.swing.JTextField Ten_4;
    private javax.swing.JTextField Ten_5;
    private javax.swing.JTextField Ten_6;
    private javax.swing.JTextField Ten_7;
    private javax.swing.JTextField Ten_8;
    private javax.swing.JTextField Ten_9;
    private javax.swing.JTextField Three_1;
    private javax.swing.JTextField Three_2;
    private javax.swing.JTextField Three_3;
    private javax.swing.JTextField Three_4;
    private javax.swing.JTextField Three_5;
    private javax.swing.JTextField Three_6;
    private javax.swing.JLabel TopBar;
    private javax.swing.JButton deleteAnswers;
    private javax.swing.JTextField one_1;
    private javax.swing.JTextField one_2;
    private javax.swing.JTextField one_3;
    private javax.swing.JTextField one_4;
    private javax.swing.JTextField one_5;
    private javax.swing.JTextField one_6;
    private javax.swing.JTextField one_7;
    private javax.swing.JTextField one_8;
    private javax.swing.JToggleButton saveAnswersBtn;
    private javax.swing.JTextField two_2;
    private javax.swing.JTextField two_3;
    private javax.swing.JTextField two_4;
    private javax.swing.JTextField two_5;
    private javax.swing.JTextField two_6;
    private javax.swing.JButton viewSavedBtn;
    // End of variables declaration//GEN-END:variables
}
