/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ibiology.Cells;

import ibiology.HomePageGUI;

/**
 *
 * @author x14500057
 */
public class CellsGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageGUI
     */
    public CellsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBar = new javax.swing.JLabel();
        TestBtn = new javax.swing.JButton();
        MiniB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();
        muteBtn = new javax.swing.JLabel();
        BoneBtn = new javax.swing.JButton();
        StemBtn = new javax.swing.JButton();
        BloodBtn = new javax.swing.JButton();
        NerveBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });

        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/button.png"))); // NOI18N
        TestBtn.setBorder(null);
        TestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TestBtnMouseClicked(evt);
            }
        });
        getContentPane().add(TestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 330, 60));

        MiniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniBMouseClicked(evt);
            }
        });
        getContentPane().add(MiniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 22, 20));

        CloseB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 10, 22, 20));
        getContentPane().add(muteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 60, 60));

        BoneBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BoneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/boneCells.png"))); // NOI18N
        BoneBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BoneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoneBtnMouseClicked(evt);
            }
        });
        BoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoneBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BoneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 150, 150));

        StemBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        StemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/stemCells.png"))); // NOI18N
        StemBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StemBtnMouseClicked(evt);
            }
        });
        StemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StemBtnActionPerformed(evt);
            }
        });
        getContentPane().add(StemBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 150, 150));
        StemBtn.getAccessibleContext().setAccessibleDescription("");

        BloodBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BloodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/bloodCells.png"))); // NOI18N
        BloodBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BloodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BloodBtnMouseClicked(evt);
            }
        });
        BloodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BloodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 150, 150));

        NerveBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NerveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/nerveCells.png"))); // NOI18N
        NerveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NerveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NerveBtnMouseClicked(evt);
            }
        });
        NerveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NerveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NerveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 150, 150));

        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/OOP_GUI_Template.png"))); // NOI18N
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundMouseClicked(evt);
            }
        });
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        setSize(new java.awt.Dimension(856, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MiniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniBMouseClicked
        this.setState(CellsGUI.ICONIFIED);
    }//GEN-LAST:event_MiniBMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x,y);
    }//GEN-LAST:event_TopBarMouseDragged

    private void BoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoneBtnActionPerformed
       BoneCellGUI GUI = new BoneCellGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_BoneBtnActionPerformed

    private void StemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StemBtnActionPerformed
       StemCellGUI GUI = new StemCellGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_StemBtnActionPerformed

    private void BloodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodBtnActionPerformed
       BloodCellGUI GUI = new BloodCellGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_BloodBtnActionPerformed

    private void NerveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NerveBtnActionPerformed
       NerveCellsGUI GUI = new NerveCellsGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_NerveBtnActionPerformed

    private void StemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StemBtnMouseClicked
       StemCellGUI GUI = new StemCellGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_StemBtnMouseClicked

    private void NerveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NerveBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NerveBtnMouseClicked

    private void BloodBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BloodBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodBtnMouseClicked

    private void BoneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoneBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BoneBtnMouseClicked

    private void BackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseClicked
        
    }//GEN-LAST:event_BackgroundMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        HomePageGUI GUI = new HomePageGUI();
        GUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void TestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TestBtnMouseClicked
        TestGUI GUI = new TestGUI();
        GUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_TestBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CellsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BloodBtn;
    private javax.swing.JButton BoneBtn;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JLabel MiniB;
    private javax.swing.JButton NerveBtn;
    private javax.swing.JButton StemBtn;
    private javax.swing.JButton TestBtn;
    private javax.swing.JLabel TopBar;
    private javax.swing.JLabel muteBtn;
    // End of variables declaration//GEN-END:variables
}
