/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ibiology.Cells;

import ibiology.Cells.CellsGUI;
import ibiology.HomePageGUI;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x14500057
 */
public class TestGUI extends javax.swing.JFrame {
    //declaring test object
    Test testObject;
    
    //declaring variables used by text object
    private String playerName, answerOne, answerTwo, answerThree, answerFour, answerFive;
    private int score;
    private int count;
    //declare arrayList of objects
    private ArrayList <Test> testList;
    
            
    //constructor
    public TestGUI() {
        initComponents();
        testObject = new Test();
        playerName = JOptionPane.showInputDialog(null, "Please enter your name:");
        testList = new ArrayList <>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        Answer1TF = new javax.swing.JTextField();
        Answer2TF = new javax.swing.JTextField();
        Answer3TF = new javax.swing.JTextField();
        Answer4TF = new javax.swing.JTextField();
        Answer5TF = new javax.swing.JTextField();
        Q1 = new javax.swing.JLabel();
        Q2 = new javax.swing.JLabel();
        Q3 = new javax.swing.JLabel();
        Q4 = new javax.swing.JLabel();
        Q5 = new javax.swing.JLabel();
        MiniB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();
        TopBar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveBtn.setBackground(new java.awt.Color(0, 255, 51));
        saveBtn.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        saveBtn.setText("Save Answer");
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 130, 60));

        viewBtn.setBackground(new java.awt.Color(51, 204, 255));
        viewBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewBtn.setText("View Answer");
        viewBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewBtn.setMargin(new java.awt.Insets(2, 8, 2, 8));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 120, 60));

        clearBtn.setBackground(new java.awt.Color(255, 51, 51));
        clearBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clearBtn.setText("Delete Answer");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.setMargin(new java.awt.Insets(2, 5, 2, 5));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 130, 60));
        clearBtn.getAccessibleContext().setAccessibleDescription("");

        Answer1TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Answer1TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 110, -1));

        Answer2TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Answer2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 110, -1));

        Answer3TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Answer3TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 110, -1));

        Answer4TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Answer4TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 110, -1));

        Answer5TF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Answer5TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, -1));

        Q1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Q1.setText("What Cells are responsible for fighting viruses?");
        getContentPane().add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 410, 40));

        Q2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Q2.setText("Which blood cells are the most common in Human Body?");
        getContentPane().add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 410, 40));

        Q3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Q3.setText("What's the name of the long part of nerve cell?");
        getContentPane().add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 410, 40));

        Q4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Q4.setText("What are leukocytes?");
        getContentPane().add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 410, 40));

        Q5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Q5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Q5.setText("What is another name for Red Blood Cells?");
        getContentPane().add(Q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 410, 40));

        MiniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniBMouseClicked(evt);
            }
        });
        getContentPane().add(MiniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 22, 20));

        CloseB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 10, 22, 20));

        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });
        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 22));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/BackB.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 170, 70));

        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });
        getContentPane().add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        Background.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/OOP_GUI_Template.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        setSize(new java.awt.Dimension(859, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MiniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniBMouseClicked
        this.setState(NerveCellsGUI.ICONIFIED);
    }//GEN-LAST:event_MiniBMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x,y);
    }//GEN-LAST:event_TopBarMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       CellsGUI GUI = new CellsGUI();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        HomePageGUI GUI = new HomePageGUI();
        GUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        
        File inFile;
        FileInputStream fileStream;
        ObjectInputStream objectStream;
        
        try{
            inFile = new File("testObject.data");
            fileStream = new FileInputStream(inFile);
            objectStream = new ObjectInputStream(fileStream);
            
            Test testObject;
            testObject = (Test)objectStream.readObject();
            
            
        if(testObject.getAnswerOne().equals("")|| testObject.getAnswerTwo().equals("")|| testObject.getAnswerThree().equals("")|| testObject.getAnswerFour().equals("")|| testObject.getAnswerFive().equals("")){
            JOptionPane.showMessageDialog(null, "There are no fully answered submissions.");
        }
        

        else if(count == 0){
            JOptionPane.showMessageDialog(null, "No answers to display!");
        }
        
        else{
            JOptionPane.showMessageDialog(null,"Player: "+ testObject.playerName + "\n Submitted following answers: \n "
                    + "Question 1: "+ testObject.getAnswerOne() 
                    +"\n Question 2: "+ testObject.getAnswerTwo() + ", "
                    +"\n Question 3: "+ testObject.getAnswerThree() +", "  
                    +"\n Question 4: "+ testObject.getAnswerFour()+ ", " 
                    +"\n Question 5: "+ testObject.getAnswerFive()+".");
            
        }
        objectStream.close();
        }
        
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_viewBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        
        if(JOptionPane.showInputDialog(null, "Please enter username to delete your answers").equals(playerName)){
            for(int i=0; i > testList.size(); i++){
            testList.remove(i);
            count--;
            System.out.println("answer deleted");
            }
            JOptionPane.showMessageDialog(null, "Player's :"+playerName + " answers have been deleted");
        }
        else if(count == 0){
            JOptionPane.showMessageDialog(null, "There are no answers saved!");
           }
        else{
            JOptionPane.showMessageDialog(null,"Player's answers cannot be find. Try again.");
            }
        
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        //File Output - Writing to file
        //Saving answers to a file
        
        answerOne = Answer1TF.getText();
        answerTwo= Answer2TF.getText();
        answerThree= Answer3TF.getText();
        answerFour = Answer4TF.getText();
        answerFive = Answer5TF.getText();
        
        testObject.setAnswerOne(answerOne);
        testObject.setAnswerTwo(answerTwo);
        testObject.setAnswerThree(answerThree);
        testObject.setAnswerFour(answerFour);
        testObject.setAnswerFive(answerFive);
        testObject.setPlayerName(playerName);

        if(Answer1TF.getText().equals("")|| Answer2TF.getText().equals("")|| Answer3TF.getText().equals("")|| Answer4TF.getText().equals("")|| Answer5TF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter asnwers into all the fields in order to save your answer");
        }
        else{
        testList.add(testObject);
        
        
        File outFile;
        FileOutputStream fileStream;
        ObjectOutputStream objectStream;
        
        try{
            outFile = new File("testObject.data");
            fileStream = new FileOutputStream(outFile);
            objectStream = new ObjectOutputStream(fileStream);
            
            objectStream.writeObject(testObject);
            
            JOptionPane.showMessageDialog(null, "Your answer has been saved successfully!");
            
            objectStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        }
        count++;
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NerveCellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NerveCellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NerveCellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NerveCellsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NerveCellsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer1TF;
    private javax.swing.JTextField Answer2TF;
    private javax.swing.JTextField Answer3TF;
    private javax.swing.JTextField Answer4TF;
    private javax.swing.JTextField Answer5TF;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JLabel MiniB;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel TopBar;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
