/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ibiology;

import javax.swing.JOptionPane;

/**
 *
 * @author x14500057
 */
public class HomePageGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageGUI
     */
    public HomePageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MiniB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();
        TopBar = new javax.swing.JLabel();
        MiniGames = new javax.swing.JLabel();
        OrgansB = new javax.swing.JLabel();
        CellsB = new javax.swing.JLabel();
        SsytemsBtn = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MiniB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniBMouseClicked(evt);
            }
        });
        getContentPane().add(MiniB, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 22, 20));

        CloseB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 10, 22, 20));

        TopBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopBarMouseDragged(evt);
            }
        });
        getContentPane().add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 22));

        MiniGames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/MinigamesBtn.png"))); // NOI18N
        MiniGames.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MiniGames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniGamesMouseClicked(evt);
            }
        });
        getContentPane().add(MiniGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 220));

        OrgansB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/OrgansBtn.png"))); // NOI18N
        OrgansB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OrgansB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrgansBMouseClicked(evt);
            }
        });
        getContentPane().add(OrgansB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 200, 220));

        CellsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/cellBtn.png"))); // NOI18N
        CellsB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CellsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CellsBMouseClicked(evt);
            }
        });
        getContentPane().add(CellsB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 200, 220));

        SsytemsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/SystemsB.png"))); // NOI18N
        SsytemsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SsytemsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SsytemsBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SsytemsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, 220));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibiology/graphics/BGHome.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 600));

        setSize(new java.awt.Dimension(858, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MiniBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniBMouseClicked
        this.setState(HomePageGUI.ICONIFIED);
    }//GEN-LAST:event_MiniBMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void TopBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x,y);
    }//GEN-LAST:event_TopBarMouseDragged

    private void CellsBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CellsBMouseClicked
        CellsGUI GUI = new CellsGUI();
        GUI.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_CellsBMouseClicked

    private void OrgansBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrgansBMouseClicked
      JOptionPane.showMessageDialog(null, "Section not completed!"); 
    }//GEN-LAST:event_OrgansBMouseClicked

    private void SsytemsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsytemsBtnMouseClicked
       SCirculatoryNotes GUI = new  SCirculatoryNotes();
       GUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_SsytemsBtnMouseClicked

    private void MiniGamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniGamesMouseClicked
        MiniGames GUI = new MiniGames();
        GUI.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_MiniGamesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CellsB;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MiniB;
    private javax.swing.JLabel MiniGames;
    private javax.swing.JLabel OrgansB;
    private javax.swing.JLabel SsytemsBtn;
    private javax.swing.JLabel TopBar;
    // End of variables declaration//GEN-END:variables
}
